version: '3.8'

services:
  db:
    image: postgres:15
    container_name: mi_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build: .
    container_name: mi_api_ollama
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - .:/app

volumes:
  postgres_data:
