"""Crear tabla CVs

Revision ID: 4fdcf96d25d4
Revises: ad4eae6a2125
Create Date: 2025-02-25 17:54:19.522941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdcf96d25d4'
down_revision: Union[str, None] = 'ad4eae6a2125'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cv', sa.Text(), nullable=False),
    sa.Column('job_desc', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cvs_id'), 'cvs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cvs_id'), table_name='cvs')
    op.drop_table('cvs')
    # ### end Alembic commands ###
