"""Crear tabla CVs

Revision ID: ad4eae6a2125
Revises: 8800e7dbf473
Create Date: 2025-02-25 17:48:01.085891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4eae6a2125'
down_revision: Union[str, None] = '8800e7dbf473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'cvs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cv', sa.Text(), nullable=False),
        sa.Column('job_desc', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
